"""
Chat Schemas - Request and Response Models for Chatbot API

This module contains the Pydantic models used for API requests and responses
in the BI Chatbot system.
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any


class QueryRequest(BaseModel):
    """Request model for chatbot questions"""

    question: str = Field(
        ...,
        min_length=1,
        max_length=1000,
        description="Business question in Hebrew",
        example="כמה לקוחות יש לי השנה?",
    )


class QueryResponse(BaseModel):
    """Response model returned by the chatbot"""

    question: str = Field(..., description="Original question")
    answer: str = Field(..., description="Answer generated by AI in Hebrew")
    sql: Optional[str] = Field(None, description="Generated SQL query")
    data: Optional[List[Dict[str, Any]]] = Field(None, description="Query results data")
    error: Optional[str] = Field(None, description="Error message if any")