"""Add multi-tenant models: Tenant, TenantUser, Session, UsageDaily, SavedReport, ReportRun, Quota, ExternalIdentity

Revision ID: cfd9d774282f
Revises: 
Create Date: 2025-11-10 01:57:11.659014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text


# revision identifiers, used by Alembic.
revision = 'cfd9d774282f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', Text(), nullable=True),  # JSON stored as Text for SQLite compatibility
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=True)
    op.create_table('quotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('monthly_token_limit', sa.Integer(), nullable=False),
    sa.Column('current_month_tokens', sa.Integer(), nullable=False),
    sa.Column('current_month_start', sa.DateTime(), nullable=False),
    sa.Column('enforce_limit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotas_id'), 'quotas', ['id'], unique=False)
    op.create_index(op.f('ix_quotas_tenant_id'), 'quotas', ['tenant_id'], unique=True)
    op.create_table('tenant_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_session_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_users_email'), 'tenant_users', ['email'], unique=True)
    op.create_index(op.f('ix_tenant_users_id'), 'tenant_users', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_users_tenant_id'), 'tenant_users', ['tenant_id'], unique=False)
    op.create_table('external_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('external_email', sa.String(length=255), nullable=True),
    sa.Column('provider_metadata', Text(), nullable=True),  # JSON stored as Text
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tenant_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uix_external_identity')
    )
    op.create_index(op.f('ix_external_identities_external_id'), 'external_identities', ['external_id'], unique=False)
    op.create_index(op.f('ix_external_identities_id'), 'external_identities', ['id'], unique=False)
    op.create_index(op.f('ix_external_identities_provider'), 'external_identities', ['provider'], unique=False)
    op.create_index(op.f('ix_external_identities_user_id'), 'external_identities', ['user_id'], unique=False)
    op.create_table('saved_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('sql_query', sa.Text(), nullable=False),
    sa.Column('parameters', Text(), nullable=True),  # JSON stored as Text
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tenant_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_reports_created_by'), 'saved_reports', ['created_by'], unique=False)
    op.create_index(op.f('ix_saved_reports_id'), 'saved_reports', ['id'], unique=False)
    op.create_index(op.f('ix_saved_reports_tenant_id'), 'saved_reports', ['tenant_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('context', Text(), nullable=True),  # JSON stored as Text
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tenant_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_sessions_tenant_id'), 'sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('usage_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('calls_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tenant_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usage_date', 'tenant_id', 'user_id', 'model', name='uix_usage_daily')
    )
    op.create_index(op.f('ix_usage_daily_id'), 'usage_daily', ['id'], unique=False)
    op.create_index(op.f('ix_usage_daily_model'), 'usage_daily', ['model'], unique=False)
    op.create_index(op.f('ix_usage_daily_tenant_id'), 'usage_daily', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_usage_daily_usage_date'), 'usage_daily', ['usage_date'], unique=False)
    op.create_index(op.f('ix_usage_daily_user_id'), 'usage_daily', ['user_id'], unique=False)
    op.create_table('report_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('executed_by', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('output_file_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['executed_by'], ['tenant_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['saved_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_runs_executed_at'), 'report_runs', ['executed_at'], unique=False)
    op.create_index(op.f('ix_report_runs_id'), 'report_runs', ['id'], unique=False)
    op.create_index(op.f('ix_report_runs_report_id'), 'report_runs', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_runs_tenant_id'), 'report_runs', ['tenant_id'], unique=False)
    op.drop_index('ix_ItemsBot2025_ID_פריט', table_name='ItemsBot2025')
    op.drop_table('ItemsBot2025')
    op.drop_index('ix_SalesBot2025_ID_מכירה', table_name='SalesBot2025')
    op.drop_table('SalesBot2025')
    op.drop_index('ix_ClientsBot2025_ID_לקוח', table_name='ClientsBot2025')
    op.drop_table('ClientsBot2025')
    op.drop_index('ix_OrdersBot2025_ID_לקוח', table_name='OrdersBot2025')
    op.drop_index('ix_OrdersBot2025_ID_מכירה', table_name='OrdersBot2025')
    op.drop_index('ix_OrdersBot2025_ID_פריט', table_name='OrdersBot2025')
    op.drop_index('ix_OrdersBot2025_תאריך', table_name='OrdersBot2025')
    op.drop_table('OrdersBot2025')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OrdersBot2025',
    sa.Column('row_id', sa.INTEGER(), nullable=True),
    sa.Column('ID_מכירה', sa.INTEGER(), nullable=False),
    sa.Column('ID_לקוח', sa.INTEGER(), nullable=False),
    sa.Column('ID_פריט', sa.INTEGER(), nullable=False),
    sa.Column('תאריך', sa.TEXT(), nullable=True),
    sa.Column('סכום', sa.REAL(), nullable=True),
    sa.ForeignKeyConstraint(['ID_לקוח'], ['ClientsBot2025.ID_לקוח'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ID_מכירה'], ['SalesBot2025.ID_מכירה'], ),
    sa.ForeignKeyConstraint(['ID_פריט'], ['ItemsBot2025.ID_פריט'], ),
    sa.PrimaryKeyConstraint('row_id')
    )
    op.create_index('ix_OrdersBot2025_תאריך', 'OrdersBot2025', ['תאריך'], unique=False)
    op.create_index('ix_OrdersBot2025_ID_פריט', 'OrdersBot2025', ['ID_פריט'], unique=False)
    op.create_index('ix_OrdersBot2025_ID_מכירה', 'OrdersBot2025', ['ID_מכירה'], unique=False)
    op.create_index('ix_OrdersBot2025_ID_לקוח', 'OrdersBot2025', ['ID_לקוח'], unique=False)
    op.create_table('ClientsBot2025',
    sa.Column('ID_לקוח', sa.INTEGER(), nullable=True),
    sa.Column('lname', sa.TEXT(), nullable=True),
    sa.Column('fname', sa.TEXT(), nullable=True),
    sa.Column('wname', sa.TEXT(), nullable=True),
    sa.Column('city', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('ID_לקוח')
    )
    op.create_index('ix_ClientsBot2025_ID_לקוח', 'ClientsBot2025', ['ID_לקוח'], unique=False)
    op.create_table('SalesBot2025',
    sa.Column('ID_מכירה', sa.INTEGER(), nullable=True),
    sa.Column('week', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('ID_מכירה')
    )
    op.create_index('ix_SalesBot2025_ID_מכירה', 'SalesBot2025', ['ID_מכירה'], unique=False)
    op.create_table('ItemsBot2025',
    sa.Column('ID_פריט', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('pgrp', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('ID_פריט')
    )
    op.create_index('ix_ItemsBot2025_ID_פריט', 'ItemsBot2025', ['ID_פריט'], unique=False)
    op.drop_index(op.f('ix_report_runs_tenant_id'), table_name='report_runs')
    op.drop_index(op.f('ix_report_runs_report_id'), table_name='report_runs')
    op.drop_index(op.f('ix_report_runs_id'), table_name='report_runs')
    op.drop_index(op.f('ix_report_runs_executed_at'), table_name='report_runs')
    op.drop_table('report_runs')
    op.drop_index(op.f('ix_usage_daily_user_id'), table_name='usage_daily')
    op.drop_index(op.f('ix_usage_daily_usage_date'), table_name='usage_daily')
    op.drop_index(op.f('ix_usage_daily_tenant_id'), table_name='usage_daily')
    op.drop_index(op.f('ix_usage_daily_model'), table_name='usage_daily')
    op.drop_index(op.f('ix_usage_daily_id'), table_name='usage_daily')
    op.drop_table('usage_daily')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_tenant_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_saved_reports_tenant_id'), table_name='saved_reports')
    op.drop_index(op.f('ix_saved_reports_id'), table_name='saved_reports')
    op.drop_index(op.f('ix_saved_reports_created_by'), table_name='saved_reports')
    op.drop_table('saved_reports')
    op.drop_index(op.f('ix_external_identities_user_id'), table_name='external_identities')
    op.drop_index(op.f('ix_external_identities_provider'), table_name='external_identities')
    op.drop_index(op.f('ix_external_identities_id'), table_name='external_identities')
    op.drop_index(op.f('ix_external_identities_external_id'), table_name='external_identities')
    op.drop_table('external_identities')
    op.drop_index(op.f('ix_tenant_users_tenant_id'), table_name='tenant_users')
    op.drop_index(op.f('ix_tenant_users_id'), table_name='tenant_users')
    op.drop_index(op.f('ix_tenant_users_email'), table_name='tenant_users')
    op.drop_table('tenant_users')
    op.drop_index(op.f('ix_quotas_tenant_id'), table_name='quotas')
    op.drop_index(op.f('ix_quotas_id'), table_name='quotas')
    op.drop_table('quotas')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
